### PR TITLE
Fix pagination

### LINKED ISSUE #26: Fix incorrect behaviour of pagination
## This issue has a bounty of $5. Please read the [contribution guide](https://github.com/slightlynerd/startupgraveyard.africa/blob/main/CONTRIBUTION.md) for instructions and terms of bounties.

**Describe the bug**
On the home page, pagination does not work correctly when a search term or filter is applied.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to landing page
2. Enter the search term "afro" in the search input
3. Notice pagination reads 1 - 3 pages, but if you click 2 or 3, it says no result found
4. Also notice that the number of startups at the top of the grid is not updated
5. The forward and backward arrows in pagination look stretched

**Expected behaviour**
1. Pagination should reflect the number of available pages
2. The number of startups is also updated according to filters
3. The forward and backward arrows in pagination are not stretched

**Screenshots**
Screenshot 2024-04-27 at 10 15 01

### PR DESCRIPTION
**Pull request by tsomic**
Fixes #26 

I also fixed the "next" button not being disabled when you're on the last page.
Also I made the "n startups" text dynamic so its singular if there's only one result.

### CODE REVIEW

**Comment by slightlynerd** [comment]
@tsomic I noticed a different bug with pagination.

Steps to reproduce:
- Go to home page
- Navigate to page 3 of startups list
- Enter "Thepeer" into search box

Expected behavior
It shows details of "Thepeer"

Actual behavior
It says "No results found"

Please can you take a look at this? Thanks.

**Comment by tsomic** [comment]
@slightlynerd sure, I'll have a look at it as soon as possible.

**Comment by tsomic** [comment]
@slightlynerd I pushed my fix

**Review by slightlynerd — APPROVED** [review]

**Comment by slightlynerd** [comment]
@tsomic I've approved the PR and will be merging it. Please reach out to me on X (https://twitter.com/slightlynerd) or drop your handle here so I can DM you for the bounty.

**Comment by tsomic** [comment]
@slightlynerd my handle is "@tsomisec"

**Pull request merged**
